# Generated by Django 4.2.3 on 2023-08-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("image", models.URLField()),
                ("imageType", models.CharField(max_length=10)),
                ("servings", models.PositiveIntegerField()),
                ("readyInMinutes", models.PositiveIntegerField()),
                ("pricePerServing", models.FloatField()),
                ("instructions", models.TextField()),
                ("cheap", models.BooleanField()),
                ("dairyFree", models.BooleanField()),
                ("ketogenic", models.BooleanField()),
                ("vegan", models.BooleanField()),
                ("vegetarian", models.BooleanField()),
                ("summary", models.TextField()),
                ("finished", models.BooleanField(default=False)),
                ("is_personalised", models.BooleanField(default=False)),
                ("ingredients", models.JSONField()),
                ("dish_type", models.JSONField()),
                ("macros", models.JSONField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
