# Generated by Django 4.2.3 on 2023-07-23 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, unique=True, upload_to="user/%Y/%m/%d/"
                    ),
                ),
                ("name", models.TextField(editable=False, max_length=40)),
                ("age", models.PositiveSmallIntegerField(editable=False)),
                (
                    "gender",
                    models.TextField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        editable=False,
                    ),
                ),
                ("City", models.TextField(max_length=40)),
                ("Country", models.TextField(editable=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietitianProfile",
            fields=[
                (
                    "userprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="panel.userprofile",
                    ),
                ),
                ("specialty", models.TextField(max_length=40)),
                ("experience", models.TextField(max_length=40)),
                ("nutritional_philosophy", models.TextField(max_length=40)),
                ("some_more", models.TextField(max_length=40)),
            ],
            bases=("panel.userprofile",),
        ),
    ]
