# Generated by Django 4.2.3 on 2023-07-23 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0002_alter_userprofile_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="name",
            new_name="full_name",
        ),
    ]
