# Generated by Django 4.2.3 on 2023-07-24 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0003_rename_name_userprofile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietitianprofile",
            name="experience",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Country",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.TextField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=40)),
                ("event_duration", models.DurationField()),
                ("date", models.DateTimeField()),
                (
                    "published_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "dietitian_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietitian_appointments",
                        to="panel.dietitianprofile",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_appointments",
                        to="panel.userprofile",
                    ),
                ),
            ],
        ),
    ]
