# Generated by Django 4.2.3 on 2023-07-25 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0004_alter_dietitianprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dietitian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="panel.dietitianprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="event_duration",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(seconds=1800), "30 minutes"),
                    (datetime.timedelta(seconds=3600), "60 minutes"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="dietitianprofile",
            name="experience",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="dietitianprofile",
            name="nutritional_philosophy",
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="dietitianprofile",
            name="some_more",
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="dietitianprofile",
            name="specialty",
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
